languageCode: "en-ca"
title: "Avalon C++ Users"

baseurl: "http://www.engr.mun.ca/~acu/"

params:
        author: "Jonathan Anderson"
        tagline: "Locally-sourced proficiency"

permalinks:
        post: "/post/:year/:month/:day/:title/"
